min_cluster_size: 1
max_cluster_size: 100000000
k_search: 50
number_of_neighbours: 50000
distance_of_neighbours: 0.1
smoothness_threshold_rad: 0.5 #30deg
curvature_threshold: 0.015 #0.02  #2e = 0.02
residual_threshold: 0.0225 # 3e = 0.045
smooth_mode_flag: true
curvature_test_flag: true
residual_test_flag: true
output_dir: /home/aichi2204/cloud2mesh_tool/src/c++/region_growing/data/tmp_10
is_coloring: true

# 点感覚[m] * 10