k_search: 50
min_cluster_size: 10
max_cluster_size: 1000000000
number_of_neighbours: 50
smoothness_threshold_rad: 0.05
curvature_threshold: 1.0
residual_threshold: 0.005
smooth_mode_flag: true
curvature_test_flag: false
residual_test_flag: true
output_dir: /home/aichi2204/ros2_ws/test/pcl-test/data/map_all_removed/5
is_coloring: true